# Generated by Django 5.1.4 on 2025-02-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contry',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
