# Generated by Django 5.1.4 on 2025-02-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_contry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contry',
            new_name='country',
        ),
    ]
