# Generated by Django 5.1.4 on 2025-02-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mariage',
            options={'ordering': ['-created_date'], 'verbose_name': 'Mariage', 'verbose_name_plural': 'Mariages'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
