# Generated by Django 5.1.4 on 2025-02-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_mariage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
