# Generated by Django 5.1.4 on 2025-02-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mariage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mariage', 'verbose_name_plural': 'Mariages'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
