# Generated by Django 5.1.4 on 2025-03-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_mariage_options_remove_event_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDay',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('birthday_celebrant', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_number', models.IntegerField(default=0)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('commune', models.CharField(blank=True, max_length=255, null=True)),
                ('avenue', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('place_or_space', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Anniversaire',
                'verbose_name_plural': 'Anniversaires',
                'ordering': ['-created_at'],
            },
            bases=('events.event',),
        ),
    ]
