# Generated by Django 5.1.4 on 2025-03-08 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_birthday_organizer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='place_or_space',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='birthday',
            old_name='guest_number',
            new_name='total_guest_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_concert', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('total_ticket_number', models.IntegerField(default=0)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('avenue', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
