# Generated by Django 5.1.4 on 2025-03-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_place_or_space_birthday_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Concert', 'verbose_name_plural': 'Concerts'},
        ),
        migrations.RemoveField(
            model_name='concert',
            name='id',
        ),
        migrations.AddField(
            model_name='concert',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event'),
            preserve_default=False,
        ),
    ]
