# Generated by Django 5.1.4 on 2025-05-01 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_concert_options_remove_concert_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conference', 'verbose_name_plural': 'Conferences'},
        ),
        migrations.AddField(
            model_name='conference',
            name='avenue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='commune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='total_guest_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conference',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
