# Generated by Django 5.1.4 on 2025-02-08 23:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_invit', models.CharField(blank=True, max_length=50, null=True, verbose_name="Code d'invitation")),
                ('invitation_type', models.CharField(choices=[('COUPLE', 'COUPLE'), ('SINGLETON', 'SINGLETON')], default='SINGLETON', max_length=50, verbose_name="Type d'invitation")),
                ('qr_code', models.ImageField(blank=True, upload_to='images/qr_code', verbose_name='Code QR')),
                ('first_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='Première personne')),
                ('second_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='Deuxième personne')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Place')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_date'],
            },
        ),
    ]
